# Documentation:
#   Enabled: false
# 
# Style/ClassAndModuleChildren:
#   Enabled: false

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 40

Metrics/ClassLength:
  CountComments: false
  Max: 200

AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'config/**/*'
    - 'bin/**'
    - 'db/**/*'
    - 'spec/**/*'
  NewCops: enable
  TargetRubyVersion: 2.6
